  {

  config.consumer_key = '1CweqPwP2qGswJ8mGgGmYQ'
  config.consumer_secret = 'IMMXkv0mPYfNnsGbwUaCM5M28OG0cD0HYU6ZvuWzv80'
  config.oauth_token = '2190741499-SS4PemM6jSJ5rsOn2PveNizNglhkC7Rt2t19uVu'
  config.oauth_token_secret = 'OFVS2RiK5wrjd8xmJ73akCoiXsggiv012ewh6YObPkEVm'
}
