TWITTER_KEY: "93TfXFST1wcRW4q7eS10Lw"
TWITTER_SECRET: "frB6YT8JAxuvEa5YetfgfGbPqAwssOuTpEKjj9c2iQ"
OAUTH_TOKEN: "24712717-YjrwFQClNf3cgCmUQx12C3VucO3riKaWxy4Sw30mv"
OAUTH_TOKEN_SECRET: "q6ModvDRj2mioDeMFGrCcy5eHWBRlePP0PF5ZcossBL5A"